create table public.admin (
  id uuid not null,
  created_at timestamp with time zone not null default now(),
  constraint admin_pkey primary key (id),
  constraint admin_id_fkey foreign KEY (id) references auth.users (id)
) TABLESPACE pg_default;

create table public.areas (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  nombre character varying not null,
  id_dependencias bigint not null,
  constraint areas_pkey primary key (id),
  constraint areas_id_dependencias_fkey foreign KEY (id_dependencias) references dependencias (id)
) TABLESPACE pg_default;

create table public.clasificacion (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  nombre character varying not null,
  constraint clasificacion_pkey primary key (id)
) TABLESPACE pg_default;

create table public.dependencias (
  id bigint generated by default as identity not null,
  nombre character varying null,
  constraint dependencia_pkey primary key (id),
  constraint dependencias_id_key unique (id)
) TABLESPACE pg_default;

create table public.estatus (
  id bigint generated by default as identity not null,
  nombre character varying null,
  constraint estatus_pkey primary key (id)
) TABLESPACE pg_default;

create table public.reportes (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  usuario_id uuid not null default auth.uid (),
  asunto character varying not null,
  descripcion text not null,
  urgencia_reporte character varying not null,
  estatus_ticket character varying not null,
  evidencias character varying null,
  dependencia_id bigint not null,
  updated_at timestamp with time zone null,
  area_id bigint null,
  clasificacion_id bigint null,
  solucion text null,
  constraint reportes_pkey primary key (id),
  constraint reportes_area_id_fkey foreign KEY (area_id) references areas (id),
  constraint reportes_clasificacion_id_fkey foreign KEY (clasificacion_id) references clasificacion (id),
  constraint reportes_dependencia_id_fkey foreign KEY (dependencia_id) references dependencias (id),
  constraint reportes_usuario_fkey foreign KEY (usuario_id) references auth.users (id)
) TABLESPACE pg_default;

create table public.ubicacion (
  id bigint generated by default as identity not null,
  nombre character varying not null,
  descripcion character varying not null,
  link character varying not null,
  constraint ubicacion_pkey primary key (id)
) TABLESPACE pg_default;

create table public.user_roles (
  id uuid not null,
  created_at timestamp with time zone not null default now(),
  role character varying not null,
  nombre text null,
  apellidos text null,
  email text null,
  constraint user_roles_pkey primary key (id),
  constraint user_roles_id_fkey foreign KEY (id) references auth.users (id)
) TABLESPACE pg_default;